# Front laser
laser_front:
  ros__parameters:
    port: /dev/ttyS0 # RS-422 bağlantısı için doğru port
    baud: 115200  # Baud rate'in doğru olduğundan emin olun
    scan_duration: 0.025  # Tarama süresi
    scan_cycle_time: 0.040  # Tarama döngü süresi
    scan_delay: 0.075  # Tarama gecikmesi
    inverted: false  # Taramanın ters olup olmadığını kontrol edin
    scan_id: 7  # Tarama kimliği
    frame_id: scan_link_0  # Frame ID
    scan_topic: scan_0  # Taramaların yayınlanacağı topic
    debug: false  # Hata ayıklama kapalı
    fields:
      '1':
        scale: 0.01  # Ölçek
        start_angle: -2.36  # Başlangıç açısı
        stop_angle: 2.36  # Bitiş açısı

laser_rear:
  ros__parameters:
    port: /dev/ttyS1 # RS-422 bağlantısı için doğru port
    baud: 115200  # Baud rate'in doğru olduğundan emin olun
    scan_duration: 0.025  # Tarama süresi
    scan_cycle_time: 0.040  # Tarama döngü süresi
    scan_delay: 0.075  # Tarama gecikmesi
    inverted: false  # Taramanın ters olup olmadığını kontrol edin
    scan_id: 7  # Tarama kimliği
    frame_id: scan_link_1  # Frame ID
    scan_topic: scan_1 # Taramaların yayınlanacağı topic
    debug: false  # Hata ayıklama kapalı
    fields:
      '1':
        scale: 0.01  # Ölçek
        start_angle: -2.36  # Başlangıç açısı
        stop_angle: 2.36  # Bitiş açısı
